/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2;

import javax.swing.JOptionPane;

/**
 *
 * @author conno
 */
public class bookingMenu extends javax.swing.JFrame {
// JFrame class for the booking menu
    
    /**
     * Creates new form bookingMenu
     */
    public bookingMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewBooking = new javax.swing.JButton();
        btnDeleteBooking = new javax.swing.JButton();
        btnAddBooking = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking Menu");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewBooking.setBackground(new java.awt.Color(242, 242, 242));
        btnViewBooking.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        btnViewBooking.setForeground(new java.awt.Color(51, 51, 51));
        btnViewBooking.setText("View a Booking");
        btnViewBooking.setBorder(null);
        btnViewBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnViewBooking.setFocusPainted(false);
        btnViewBooking.setMaximumSize(new java.awt.Dimension(150, 100));
        btnViewBooking.setMinimumSize(new java.awt.Dimension(150, 100));
        btnViewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookingActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 250, 110));

        btnDeleteBooking.setBackground(new java.awt.Color(242, 242, 242));
        btnDeleteBooking.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        btnDeleteBooking.setForeground(new java.awt.Color(51, 51, 51));
        btnDeleteBooking.setText("Delete a Booking");
        btnDeleteBooking.setBorder(null);
        btnDeleteBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeleteBooking.setFocusPainted(false);
        btnDeleteBooking.setMaximumSize(new java.awt.Dimension(150, 100));
        btnDeleteBooking.setMinimumSize(new java.awt.Dimension(150, 100));
        btnDeleteBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookingActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 250, 110));

        btnAddBooking.setBackground(new java.awt.Color(242, 242, 242));
        btnAddBooking.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        btnAddBooking.setForeground(new java.awt.Color(51, 51, 51));
        btnAddBooking.setText("Add a Booking");
        btnAddBooking.setBorder(null);
        btnAddBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAddBooking.setFocusPainted(false);
        btnAddBooking.setMaximumSize(new java.awt.Dimension(150, 100));
        btnAddBooking.setMinimumSize(new java.awt.Dimension(150, 100));
        btnAddBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookingActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, 110));

        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText(" ← Back  ");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 20));

        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("⏏ Exit ");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 20));

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/pg bg.png"))); // NOI18N
        bgimage.setText("jLabel1");
        getContentPane().add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookingActionPerformed
        // Button navigates user to the view booking JFrame class
        // menu Frame is set invisible instead of disposing for memmory effeciancy 
        this.setVisible(false);
        viewBooking vb = new viewBooking();
        vb.setVisible(true);
    }//GEN-LAST:event_btnViewBookingActionPerformed

    private void btnDeleteBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookingActionPerformed
        // Button navigates user to the delete booking JFrame class
        // menu Frame is set invisible instead of disposing for memmory effeciancy
        this.setVisible(false);
        deleteBooking db = new deleteBooking();
        db.setVisible(true);
        
    }//GEN-LAST:event_btnDeleteBookingActionPerformed

    private void btnAddBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookingActionPerformed
        // Button navigates user to the add booking JFrame class
        // menu Frame is set invisible instead of disposing for memmory effeciancy
        addBooking ab = new addBooking();
        ab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddBookingActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Button allows users to navigate to previous menu
        this.setVisible(false);
        menu m = new menu();
        m.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Button method to exit the program
        // Option to confirm action
        int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "Alert", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
        } else if (option == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "Okay, exit  terminated", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgimage;
    private javax.swing.JButton btnAddBooking;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteBooking;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnViewBooking;
    // End of variables declaration//GEN-END:variables
}
