/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2;

import javax.swing.JOptionPane;

/**
 *
 * @author conno
 */
public class viewRoom extends javax.swing.JFrame {
// JFrame class for viewing rooms
    
    /**
     * Creates new form viewRoom
     */
    public viewRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRoomId = new javax.swing.JTextField();
        lblRoomType = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblType = new javax.swing.JLabel();
        lblFloor = new javax.swing.JLabel();
        lblCapacity = new javax.swing.JLabel();
        lblRoomID = new javax.swing.JLabel();
        txtRoomID = new javax.swing.JTextField();
        txtCapacity = new javax.swing.JTextField();
        txtFloor = new javax.swing.JTextField();
        txtRoomNo = new javax.swing.JTextField();
        lblNoPc = new javax.swing.JLabel();
        lblOS = new javax.swing.JLabel();
        txtOS = new javax.swing.JTextField();
        txtNoPc = new javax.swing.JTextField();
        txtSeating = new javax.swing.JTextField();
        lblSeating = new javax.swing.JLabel();
        txtMic = new javax.swing.JTextField();
        lblMic = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        lblRoomNo1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Room");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtRoomId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, -1));

        lblRoomType.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblRoomType.setForeground(new java.awt.Color(255, 255, 255));
        lblRoomType.setText("Enter Room ID:");
        getContentPane().add(lblRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText(" ← Back  ");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 20));

        lblType.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblType.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        lblFloor.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblFloor.setForeground(new java.awt.Color(255, 255, 255));
        lblFloor.setText("Floor:");
        getContentPane().add(lblFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        lblCapacity.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblCapacity.setForeground(new java.awt.Color(255, 255, 255));
        lblCapacity.setText("Capacity:");
        getContentPane().add(lblCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        lblRoomID.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblRoomID.setForeground(new java.awt.Color(255, 255, 255));
        lblRoomID.setText("Room ID:");
        getContentPane().add(lblRoomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        txtRoomID.setEditable(false);
        getContentPane().add(txtRoomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 200, -1));

        txtCapacity.setEditable(false);
        getContentPane().add(txtCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 200, -1));

        txtFloor.setEditable(false);
        getContentPane().add(txtFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 200, -1));

        txtRoomNo.setEditable(false);
        getContentPane().add(txtRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 200, -1));

        lblNoPc.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblNoPc.setForeground(new java.awt.Color(255, 255, 255));
        lblNoPc.setText("No. of PC's:");
        getContentPane().add(lblNoPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        lblOS.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblOS.setForeground(new java.awt.Color(255, 255, 255));
        lblOS.setText("OS:");
        getContentPane().add(lblOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        txtOS.setEditable(false);
        getContentPane().add(txtOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 200, -1));

        txtNoPc.setEditable(false);
        getContentPane().add(txtNoPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 200, -1));

        txtSeating.setEditable(false);
        getContentPane().add(txtSeating, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 200, -1));

        lblSeating.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblSeating.setForeground(new java.awt.Color(255, 255, 255));
        lblSeating.setText("Tiered Seating:");
        getContentPane().add(lblSeating, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        txtMic.setEditable(false);
        getContentPane().add(txtMic, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 200, -1));

        lblMic.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblMic.setForeground(new java.awt.Color(255, 255, 255));
        lblMic.setText("Mic Type:");
        getContentPane().add(lblMic, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 163, 790, 10));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        lblRoomNo1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblRoomNo1.setForeground(new java.awt.Color(255, 255, 255));
        lblRoomNo1.setText("Room No:");
        getContentPane().add(lblRoomNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("⏏ Exit ");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/pg bg.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Button allows users to navigate to previous menu
        this.setVisible(false);
        roomMenu rm = new roomMenu();
        rm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    // Get the room ID entered by the user
    String roomId = txtRoomId.getText();
    
    // Search for the room in labRoomLst
    for (labRoom lab : AppLib.labRoomLst) {
        if (lab.getRoomId().equals(roomId)) {
            // Room found in labRoomLst
            // Fill the text fields with lab room details
            lblMic.setVisible(false);
            lblSeating.setVisible(false);
            txtMic.setVisible(false);
            txtSeating.setVisible(false);
            lblType.setText("Lab Room");
            txtRoomNo.setText(String.valueOf(lab.getRoomNumber()));
            txtFloor.setText(String.valueOf(lab.getFloor()));
            txtCapacity.setText(String.valueOf(lab.getCapacity()));
            txtNoPc.setText(String.valueOf(lab.getNumberOfPcs()));
            txtOS.setText(lab.getOperatingSystems());
            txtSeating.setText("");
            txtMic.setText("");
            txtRoomID.setText(roomId);
            return; // Exit the method after populating the fields
        }
    }
    
    // If room is not found in labRoomLst, then it searches in lectureHallLst
    for (lectureHall lecture : AppLib.lectureHallLst) {
        if (lecture.getRoomId().equals(roomId)) {
            // Room found in lectureHallLst
            // Fill the text fields with lecture hall details
            lblOS.setVisible(false);
            lblNoPc.setVisible(false);
            txtOS.setVisible(false);
            txtNoPc.setVisible(false);
            lblType.setText("Lecture Hall");
            txtRoomNo.setText(lecture.getRoomId());
            txtFloor.setText(Integer.toString(lecture.getFloor()));
            txtCapacity.setText(String.valueOf(lecture.getCapacity()));
            if (lecture.getTieredSeating() == true){
                txtSeating.setText("True");
            }
            else{
                txtSeating.setText("false");
            }
            txtMic.setText(lecture.getMicrophoneType());
            txtNoPc.setText(""); 
            txtOS.setText(""); 
            txtRoomID.setText(roomId);
            return; // Exit the method after populating the fields
        }
    }
    
    // If room is not found in both lists, display an error message
    JOptionPane.showMessageDialog(rootPane, "Room ID not found!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Button method to exit the program
        // Option to confirm action
        int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "Alert", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
        } else if (option == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "Okay, exit  terminated", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblFloor;
    private javax.swing.JLabel lblMic;
    private javax.swing.JLabel lblNoPc;
    private javax.swing.JLabel lblOS;
    private javax.swing.JLabel lblRoomID;
    private javax.swing.JLabel lblRoomNo1;
    private javax.swing.JLabel lblRoomType;
    private javax.swing.JLabel lblSeating;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtFloor;
    private javax.swing.JTextField txtMic;
    private javax.swing.JTextField txtNoPc;
    private javax.swing.JTextField txtOS;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtRoomId;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtSeating;
    // End of variables declaration//GEN-END:variables
}
